
# Git Stuff
brew 'git'
brew 'git-flow'
brew 'hub'


# Dev Stuff
brew 'node'
brew 'npm'
brew 'nvm'
brew 'python'
brew 'rbenv'
brew 'rbenv-vars'
brew 'ruby-build'
brew 'openssl'
brew 'heroku-toolbelt'
brew 'imagemagick'
brew 'libyaml'
brew 'packer'
brew 'postgres', restart_service: true
brew 'redis', restart_service: true
brew 'tag'
brew 'zsh-syntax-highlighting'


# ZSH Stuff
brew 'zsh'
brew 'zsh-completions'
brew 'zsh-syntax-highlighting'


# Terminal Tools
brew 'mas'
brew 'ngrok'
brew 'wget'
